---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)

counts <- fread("counts.csv")
counts[, sample := tstrsplit(sample, "-")[[3]]]
counts[, mouse := substr(sample, 1, 2)]
counts[, day := as.numeric(substr(sample, 4, 6))]

counts$responder <- "responder"
counts[mouse %in% c("A4", "A5", "C6", "C7"), responder := "non-responder"]

counts
```

```{r}
library(ggplot2)

resistance <- counts[, .(counts = sum(counts), reads=reads[1], day=day[1], mouse=mouse[1], responder=responder[1]), by="sample"]
beta <- counts[grepl("beta-lactamase", description), 
               .(counts = sum(counts), reads=reads[1], day=day[1], mouse=mouse[1], responder=responder[1]), by="sample"]
time_plot <- ggplot(beta, aes(x=responder, y=counts/reads, color=mouse)) + 
  geom_boxplot(color="gray") + geom_jitter(size=2, width=0.25) + 
  facet_wrap(~day) + theme_bw()
time_plot
ggsave("beta_time.png", width=10, height=5)
```

```{r}
time_plot %+% resistance
ggsave("resistance_time.png", width=10, height=5)
```

```{r}
mouse_plot <- ggplot(beta, aes(x=factor(day), y=counts/reads, color=mouse)) + 
  geom_point(size=2) + geom_line(aes(group=mouse)) + facet_wrap(~ mouse) + theme_bw()
mouse_plot
ggsave("beta_time.png")
```

```{r}
mouse_plot %+% resistance
ggsave("resistance_time.png")
```