---
title: "Differential transcript abundances"
output: html_notebook
---

## Data reading and preprocesing

```{r}
library(mbtools)

counts <- fread("data/txcounts.csv")
counts[, sample := tstrsplit(sample, "-")[[3]]]
counts[, counts := round(counts)]
counts[counts > 0]
counts <- dcast(counts, transcript ~ sample, fill=0, value.var = "counts")
nm <- counts[, transcript]
counts[, transcript := NULL]
counts <- as.matrix(counts)
rownames(counts) <- nm

meta <- fread("data/seq_samples.csv", key="Sample")[colnames(counts)]
meta[, day := substr(Sample, 4, 6)]
meta[, mouse := substr(Sample, 1, 3)]
meta
```

We will also filter low abundance transcripts from the count matrix.

```{r}
counts <- t(filter_counts(t(counts), abundance = 10, presence = 0.5))
nrow(counts)
```

Let's look at the samples.

```{r, fig.width=6, fig.height=4}
pca <- prcomp(log2(mbtools::normalize(t(counts))+0.5))
explained <- pca$sdev^2 / sum(pca$sdev^2)
red <- as.data.table(pca$x)
red[, sample := rownames(pca$x)]
red <- meta[red, on=c(Sample="sample")]
ggplot(red, aes(x = PC1, y = PC2, shape = day, color = type)) + geom_point(size=2) +
  labs(x = sprintf("PC1 (%.1f%%)", explained[1] * 100), y = sprintf("PC2 (%.1f%%)", explained[2] * 100)) +
  theme_bw()
ggsave("data/transcript_pca.svg", width=6, height=4)
```

## With responders

```{r}
library(DESeq2)

ds <- DESeqDataSetFromMatrix(counts[, meta$day == 29], meta[day == 29], ~ type)
ds <- DESeq(ds, parallel = TRUE)
res <- results(ds)
res <- lfcShrink(ds, 2, parallel = TRUE)
```

We will merge this with the annotations for the contigs.

```{r}
dif <- as.data.table(res)
dif[, transcript := rownames(res)]

anns <- fread("data/contig_seed.csv")
dif <- anns[dif, on=c(query="transcript")]
sig <- dif[padj < 0.05, .(query, description, log2FoldChange, padj)][order(padj)]
```

However if we compare the dimensions:

```{r}
dif[, table(padj < 0.05)]
```

So about 40% of all tests are significant.